### ISSUE TITLE
installation as a package ?

### ISSUE THREAD

**Issue by sbrun** [RhinoSecurityLabs/pacu#230]
Hello,

I started to work on packaging pacu for Kali linux (https://bugs.kali.org/view.php?id=7030)

From what I see you don't provide a way to install in a system wide manner (FHS compliant).
Several files/directories are created or rewritten in pacu directory (like settings.py or global_error_log.txt files) and in sessions and modules directories.
If I installed pacu in /usr/share/pacu (like it should be I think), the user will have no access to modify the files and he will not be able to use pacu.
Do you have recommendations to install pacu in this way?

If you need to write files they should in $HOME/.local/share or maybe other directories depending on the use of the files:
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by RyanJarv** [comment]
I'll have to look into if there's a straightforward way of doing this.

Worst case if this isn't we are looking into potentially refactoring Pacu, If that happens first this would be a good thing to include.

**Comment by RyanJarv** [comment]
This is still a work in progress but linked the PR I'm using for moving to a common output/config directory.

I think for now I'd like to avoid moving things around to much so I'm essentially just adding moving things to ~/.local/share/pacu through a common setting. I'm not sure how much it makes sense to strictly adhere to FHS beyond that (or is that enough?), but I think either way we can come back and change things later. Most of the changes here is just un-hardcoding everything.

@sbrun Let me know if you have any thoughts on this.

**Comment by RyanJarv** [comment]
One other thing I'm wondering, just in case you see this before I dig into it much is how Kali Linux packages pip packages. If this was installable through pip would that be enough to get it set up through dpkg or is there any thing else to be aware of there?

**Comment by RyanJarv** [comment]
@sbrun I'm testing packaging with dh-python on https://github.com/RhinoSecurityLabs/pacu/tree/test/debian-packaging (debian files there where copied from another Kali python package and likely are not completely correct).

This seems to more or less work (needs more testing still) but one issue I could use some input on is we rely on https://github.com/RhinoSecurityLabs/dsnap for one of the modules which seems to get omitted when building the package, I imagine this is because this only exists in pip.

Does that need to be packaged as well and if so will the pyproject.toml style setup work here (as opposed to using setuptools)?

I'll likely be merging #247 in sometime soon (after more testing) which should take care of the output directory issues. This also get's things setup so we can push Pacu to PyPi.

If you can let me know if the dsnap dependency will be an issue and if there is anything I can do there to help that would be appreciated.

**Comment by sbrun** [comment]
Thanks for working on this

**Comment by sbrun** [comment]
We don't use pip to install packages or to build python packages.
I will have to create a separate package for dnsap. It's not a problem. The package can be created quite quickly with the Debian packaging tools even if it uses poetry: poetry is not yet available in Debian (people are working on that) but it's not a problem for the packaging.

**Comment by sbrun** [comment]
If you change the Pacu structure code to be able to push it on pip, it will also be easier for the packaging work (for Kali and other distributions).
I will package dsnap for Kali. I will let you know when it is available in the kali repository.

**Comment by sbrun** [comment]
Hello!
dsnap (package python3-dsnap) is in kali-rolling.

**Comment by RyanJarv** [comment]
Just realized this got closed because it was referenced as a linked issue in the PR. Will open it back up for now, but we should be good here now.

Let me know if you run into any issues!

**Comment by sbrun** [comment]
Hello.
I packaged Pacu for Kali without problem. It's in available in Kali repo and it has been tested.
Thanks for your work on this issue!

**Comment by RyanJarv** [comment]
Awesome! Great to have this available via the Kali repo, know I'll be making use of this.

Let us know if you ever run into issues or can use any help with maintaining the package.
